namespace DeBron.PowerPoint.Builder;

public static class Constants
{
    public static Dictionary<string, string> Biblebooks = new Dictionary<string, string>()
    {
        { "Genesis", "GEN" },
        { "Exodus", "EXO" },
        { "Leviticus", "LEV" },
        { "Numeri", "NUM" },
        { "Deuteronomium", "DEU" },
        { "Jozua", "JOS" },
        { "Rechters", "JDG" },
        { "Ruth", "RUT" },
        { "1 Samuel", "1SA" },
        { "2 Samuel", "2SA" },
        { "1 Koningen", "1KI" },
        { "2 Koningen", "2KI" },
        { "1 Kronieken", "1CH" },
        { "2 Kronieken", "2CH" },
        { "Ezra", "EZR" },
        { "Nehemia", "NEH" },
        { "Ester", "EST" },
        { "Job", "JOB" },
        { "Psalmen", "PSA" },
        { "Spreuken", "PRO" },
        { "Prediker", "ECC" },
        { "Hooglied", "SNG" },
        { "Jesaja", "ISA" },
        { "Jeremia", "JER" },
        { "Klaagliederen", "LAM" },
        { "Ezechiël", "EZK" },
        { "Daniël", "DAN" },
        { "Hosea", "HOS" },
        { "Joël", "JOL" },
        { "Amos", "AMO" },
        { "Obadja", "OBA" },
        { "Jona", "JON" },
        { "Micha", "MIC" },
        { "Nahum", "NAM" },
        { "Habakuk", "HAB" },
        { "Sefanja", "ZEP" },
        { "Haggai", "HAG" },
        { "Zacharia", "ZEC" },
        { "Maleachi", "MAL" },
        { "Tobit", "TOB" },
        { "Judit", "JDT" },
        { "Ester (Gr.)", "ESG" },
        { "1 Makkabeeën", "1MA" },
        { "2 Makkabeeën", "2MA" },
        { "Wijsheid", "WIS" },
        { "Sirach", "SIR" },
        { "Baruch", "BAR" },
        { "Brief van Jeremia", "LJE" },
        { "Manasse", "MAN" },
        { "Daniël (Gr.)", "DAG" },
        { "Matteüs", "MAT" },
        { "Marcus", "MRK" },
        { "Lucas", "LUK" },
        { "Johannes", "JHN" },
        { "Handelingen", "ACT" },
        { "Romeinen", "ROM" },
        { "1 Korintiërs", "1CO" },
        { "2 Korintiërs", "2CO" },
        { "Galaten", "GAL" },
        { "Efeziërs", "EPH" },
        { "Filippenzen", "PHP" },
        { "Kolossenzen", "COL" },
        { "1 Tessalonicenzen", "1TH" },
        { "2 Tessalonicenzen", "2TH" },
        { "1 Timoteüs", "1TI" },
        { "2 Timoteüs", "2TI" },
        { "Titus", "TIT" },
        { "Filemon", "PHM" },
        { "Hebreeën", "HEB" },
        { "Jakobus", "JAS" },
        { "1 Petrus", "1PE" },
        { "2 Petrus", "2PE" },
        { "1 Johannes", "1JN" },
        { "2 Johannes", "2JN" },
        { "3 Johannes", "3JN" },
        { "Judas", "JUD" },
        { "Openbaring", "REV" }
    };
}